-- ============================================================
-- Admin bootstrap: vacunawa@rhu.com.ph / admin123
-- IMPORTANT: auth.users passwords are hashed by GoTrue — you CANNOT
-- insert this user with plain SQL. Do ONE of the options below,
-- then link the profiles row.
-- ============================================================

-- ---------- OPTION A (recommended): Supabase Dashboard ----------
-- 1. Go to Authentication > Users > Add user > Create new user
--    Email:    vacunawa@rhu.com.ph
--    Password: admin123
--    [x] Auto Confirm User
-- 2. Copy the new user's UUID, then run:
--
-- insert into profiles (id, full_name, role)
-- values ('<PASTE_UUID_HERE>', 'RHU Admin', 'admin')
-- on conflict (id) do update set role = 'admin', full_name = 'RHU Admin';
--
-- 3. Verify:
-- select id, full_name, role from profiles where id = '<PASTE_UUID_HERE>';
-- EXPECTED: role = 'admin'

-- ---------- OPTION B: Auth Admin API with service_role ----------
-- From any machine with the service_role key (NEVER ship it in frontend):
--
-- curl -X POST "https://<PROJECT_REF>.supabase.co/auth/v1/admin/users" \
--   -H "apikey: <SERVICE_ROLE_KEY>" \
--   -H "Authorization: Bearer <SERVICE_ROLE_KEY>" \
--   -H "Content-Type: application/json" \
--   -d '{"email":"vacunawa@rhu.com.ph","password":"admin123","email_confirm":true,"user_metadata":{"full_name":"RHU Admin"}}'
--
-- Then insert into profiles as in Option A step 2 using the returned id.

-- ---------- OPTION C: one-off Node script (see create_admin.cjs) ----------
-- node create_admin.cjs  (needs SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY env vars)

-- ---------- Board/kiosk accounts (do after admin works) ----------
-- Same flow, role='board', e.g. email board-kiosk-01@rhu.local:
-- insert into profiles (id, full_name, role, device_label)
-- values ('<BOARD_UUID>', 'Lobby Kiosk 01', 'board', 'lobby-kiosk-01')
-- on conflict (id) do update set role='board', device_label='lobby-kiosk-01';
